name: Build OnePluss-Sm8250-Kernel
on:
  workflow_dispatch:
  schedule:
      # Run once a week on Sunday at midnight. See http://crontab.guru
      - cron: '0 21 * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KERNEL_DEFCONFIG: "sm8250_defconfig"
      KERNEL_CMDLINE: "ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LLVM=1 LLVM_IAS=1 O=out"
      ARCH: arm64
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: oss13
        fetch-depth: 10

    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Install dependencies
      run: |
        sudo apt-get update -y 
        sudo apt install gcc-aarch64-linux-gnu -y
        sudo apt install gcc-arm-linux-gnueabi -y
        sudo apt install binutils make python3 libssl-dev build-essential bc  bison flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs -y
        git clone https://codeberg.org/Mandi-Sa/clang --dept=1 -b amd64-kernel-arm
        git clone https://github.com/lateautumn233/AnyKernel3 -b master --depth=1
        rm -rf AnyKernel3/.git
    
    - name: GetTime
      id: get_time
      run: |
        echo "TIME=$(TZ=UTC-8 date +%m%d%H%M )" >> $GITHUB_OUTPUT

    - name: Build Kernel-SU
      run: |
        curl -SsL https://github.com/tiann/kernelsu/raw/main/kernel/setup.sh | bash
        sed -i '/config KSU/,/help/{s/default y/default m/}' drivers/kernelsu/Kconfig

        export PATH=$(pwd)/clang/bin/:$PATH
        mkdir out
        make $KERNEL_CMDLINE $KERNEL_DEFCONFIG CC=clang
        make $KERNEL_CMDLINE CC=clang -j$(nproc --all)
        test -f out/drivers/kernelsu/kernelsu.ko && cp out/drivers/kernelsu/kernelsu.ko Anykernel3
        cp out/arch/arm64/boot/Image.gz AnyKernel3

    - name: Upload Kernel-SU
      uses: actions/upload-artifact@v3
      with:
        name: Qiuqiu-kernel-SU-${{ steps.get_time.outputs.TIME }}
        path: "AnyKernel3/*"
